name: 'user_srv'
port: 8082
user_srv:
  host: '127.0.0.1'
  port: 8080
jwtinfo:
  signingKey: '0VtZ^Qe*Y1KrlWaY#dk3'

aliyunInfo:
  accessKeyId: ''
  accessKeySecret: ''
  SignName: ''
  TemplateCode: ''

redisInfo:
  host: '192.168.226.108'
  port: 6379